// <url>
//     <loc>https://doxius.com/resize-image</loc>
//     <priority>0.8</priority>
//     <changefreq>monthly</changefreq>
//     <lastmod>2026-01-26</lastmod>
//   </url>
//   <url>
//     <loc>https://doxius.com/jpg-to-pdf</loc>
//     <priority>0.9</priority>
//     <changefreq>monthly</changefreq>
//     <lastmod>2026-01-26</lastmod>
//   </url>
//   <url>
//     <loc>https://doxius.com/word-to-pdf</loc>
//     <priority>0.9</priority>
//     <changefreq>monthly</changefreq>
//     <lastmod>2026-01-26</lastmod>
//   </url>
//   <url>
//     <loc>https://doxius.com/pdf-to-word</loc>
//     <priority>0.9</priority>
//     <changefreq>monthly</changefreq>
//     <lastmod>2026-01-26</lastmod>
//   </url>
//   <url>
//     <loc>https://doxius.com/pdf-to-jpg</loc>
//     <priority>0.9</priority>
//     <changefreq>monthly</changefreq>
//     <lastmod>2026-01-26</lastmod>
//   </url>
//   <url>
//     <loc>https://doxius.com/merge-pdf</loc>
//     <priority>0.9</priority>
//     <changefreq>monthly</changefreq>
//     <lastmod>2026-01-26</lastmod>
//   </url>
//   <url>
//     <loc>https://doxius.com/split-pdf</loc>
//     <priority>0.9</priority>
//     <changefreq>monthly</changefreq>
//     <lastmod>2026-01-26</lastmod>
//   </url>
//   <url>
//     <loc>https://doxius.com/compress-pdf</loc>
//     <priority>0.8</priority>
//     <changefreq>monthly</changefreq>
//     <lastmod>2026-01-26</lastmod>
//   </url>